### ISSUE TITLE
Which defconfig should I use for k210?

### ISSUE THREAD

**Issue by ClankPan** [damien-lemoal/buildroot#4]
I'd like to build nommu linux for maixduino. Which defconfig should I use?

**Comment by damien-lemoal** [comment]
See board/sipeed/maixduino/readme.txt

**Comment by damien-lemoal** [comment]
And please use the official buildroot tree. This tree now not up-to-date. All the Sipeed boards support is now upstream in the official buildroot tree, master branch.
